=== oldsharp/appia/appia/config/xml/appiaxml.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT appia (template*,channel*)>
<!ATTLIST appia
	multischedulers (yes|no) #IMPLIED
	scheduler CDATA #IMPLIED>
<!ELEMENT template (session+)>
<!ATTLIST template 
	name CDATA #REQUIRED>
<!ELEMENT session (protocol)>
<!ATTLIST session 
	name CDATA #REQUIRED 
	sharing (private|label|global) #REQUIRED>
<!ELEMENT protocol (#PCDATA)>
<!ELEMENT channel (memorymanagement*,chsession*)>
<!ATTLIST channel
	name CDATA #REQUIRED
	template CDATA #REQUIRED
	initialized (yes|no) #REQUIRED
	label CDATA #IMPLIED>
<!ELEMENT chsession (parameter*)>
<!ATTLIST chsession
	name CDATA #REQUIRED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED>
<!ELEMENT memorymanagement (size*,up_threshold*,down_threshold*)>
<!ATTLIST memorymanagement
	size CDATA #REQUIRED
	up_threshold CDATA #REQUIRED
	down_threshold CDATA #REQUIRED>

=== oldsharp/appia/config/demo/Reconfigurator.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
	"../xml/appiaxml.dtd">
<appia>
	<template name="ecco_t">
		<session name="tcp_s" sharing="private">
			<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
		</session>
		<session name="reconfig_s" sharing="global">
			<protocol>net.sf.appia.protocols.reconfigurator.ReconfiguratorLayer</protocol>
		</session>
		<session name="ecco_s" sharing="private">
			<protocol>net.sf.appia.test.xml.ecco.EccoLayer</protocol>
		</session>
	</template>
	<template name="reconfig_t">
		<session name="tcp_s" sharing="private">
			<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
		</session>
		<session name="reconfig_s" sharing="global">
			<protocol>net.sf.appia.protocols.reconfigurator.ReconfiguratorLayer</protocol>
		</session>
	</template>
	

	<channel name="ecco_c" template="ecco_t" initialized="yes">
		<chsession name="ecco_s">
			<parameter name="localport">4001</parameter>
			<parameter name="remotehost">localhost</parameter>
			<parameter name="remoteport">4000</parameter>
		</chsession>
	</channel>
	<channel name="manager_c" template="reconfig_t" initialized="yes">
		<chsession name="reconfig_s">
			<parameter name="localport">4002</parameter>
			<parameter name="remotehost">localhost</parameter>
			<parameter name="remoteport">4003</parameter>
		</chsession>
	</channel>	
	
</appia>

=== oldsharp/appia/appia/config/demo/managed_perf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
	"http://appia.di.fc.ul.pt/xml/3.2/appiaxml.dtd">
<appia>
	<template name="Perf Udp+Fifo Template">
	<session name="udp" sharing="private">
		<protocol>org.continuent.appia.protocols.udpsimple.UdpSimpleLayer</protocol>
	</session>
	<session name="fifo" sharing="private">
		<protocol>org.continuent.appia.protocols.fifo.FifoLayer</protocol>
	</session>
	<session name="frag" sharing="private">
		<protocol>org.continuent.appia.protocols.frag.FragLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>org.continuent.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>org.continuent.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>org.continuent.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>org.continuent.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>org.continuent.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>

	<template name="Perf Udp+NakFifo Template">
	<session name="udp" sharing="private">
		<protocol>org.continuent.appia.protocols.udpsimple.UdpSimpleLayer</protocol>
	</session>
	<session name="nakfifo" sharing="private">
		<protocol>org.continuent.appia.protocols.nakfifo.NakFifoLayer</protocol>
	</session>
	<session name="frag" sharing="private">
		<protocol>org.continuent.appia.protocols.frag.FragLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>org.continuent.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>org.continuent.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>org.continuent.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>org.continuent.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>org.continuent.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>

	<template name="Perf Tcp Template">
	<session name="tcp" sharing="private">
		<protocol>org.continuent.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>org.continuent.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>org.continuent.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>org.continuent.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>org.continuent.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>org.continuent.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>

	<template name="Perf Udp+NakFifoMulticast Template">
	<session name="udp" sharing="private">
		<protocol>org.continuent.appia.protocols.udpsimple.UdpSimpleLayer</protocol>
	</session>
	<session name="nakfifo" sharing="private">
		<protocol>org.continuent.appia.protocols.nakfifo.multicast.NakFifoMulticastLayer</protocol>
	</session>
	<session name="frag" sharing="private">
		<protocol>org.continuent.appia.protocols.frag.FragLayer</protocol>
	</session>
	<session name="gbl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.bottom.GroupBottomLayer</protocol>
	</session>
	<session name="gol" sharing="private">
		<protocol>org.continuent.appia.protocols.group.heal.GossipOutLayer</protocol>
	</session>
	<session name="suspectl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.suspect.SuspectLayer</protocol>
	</session>		
	<session name="intral" sharing="private">
		<protocol>org.continuent.appia.protocols.group.intra.IntraLayer</protocol>
	</session>
	<session name="interl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.inter.InterLayer</protocol>
	</session>
	<session name="hl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.heal.HealLayer</protocol>
	</session>
	<session name="stablel" sharing="private">
		<protocol>org.continuent.appia.protocols.group.stable.StableLayer</protocol>
	</session>
	<session name="ll" sharing="private">
		<protocol>org.continuent.appia.protocols.group.leave.LeaveLayer</protocol>
	</session>
	<session name="vsl" sharing="private">
		<protocol>org.continuent.appia.protocols.group.sync.VSyncLayer</protocol>
	</session>
	<session name="perf" sharing="private">
		<protocol>org.continuent.appia.test.perf.PerfLayer</protocol>
	</session>
	</template>
	
	<management naming_port="1099" />

	<channel name="Perf Channel" template="Perf Udp+NakFifoMulticast Template" initialized="yes" managed="yes">
		<chsession name="perf">
			<!-- Example for ring test with two members and IP-Multicast address for gossip dissemination. -->
			<parameter name="n">2</parameter>
			<parameter name="k">100</parameter>
			<parameter name="r">10</parameter>
			<parameter name="m">100</parameter>
			<parameter name="gossip">224.0.0.3:10001</parameter>
		</chsession>
	</channel>

</appia>

=== oldsharp/appia/appia/config/demo/ecco2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
	"../xml/appiaxml.dtd">
<appia>
	<template name="ecco_t">
		<session name="tcp_s" sharing="global">
			<protocol>org.continuent.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
		</session>
		<session name="ecco_s" sharing="private">
			<protocol>org.continuent.appia.test.xml.ecco.EccoLayer</protocol>
		</session>
	</template>
	<channel name="ecco_c" template="ecco_t" initialized="yes">
		<chsession name="ecco_s">
			<parameter name="localport">4001</parameter>
			<parameter name="remotehost">localhost</parameter>
			<parameter name="remoteport">4000</parameter>
		</chsession>
	</channel>
</appia>

=== oldsharp/appia/config/demo/Amanager.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appia PUBLIC "-//DTDName//DTD//EN"
	"../xml/appiaxml.dtd">
<appia>
	<template name="ecco_t">
		<session name="tcp_s" sharing="global">
			<protocol>net.sf.appia.protocols.tcpcomplete.TcpCompleteLayer</protocol>
		</session>
		<session name="reconfig_s" sharing="private">
			<protocol>net.sf.appia.adaptationmanager.AdaptationManagerLayer</protocol>
		</session>
	</template>
	<channel name="manager_c" template="ecco_t" initialized="yes">
		<chsession name="reconfig_s">
			<parameter name="localport">4003</parameter>
			<parameter name="remotehost">localhost</parameter>
			<parameter name="remoteport">4002</parameter>
		</chsession>
	</channel>
</appia>
